### PR TITLE
Compile against oldest supported numpy, fixes #18

### LINKED ISSUE #18: "module compiled against API version 0xe but this version of numpy is 0xd"
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:  module compiled against API version 0xe but this version of numpy is 0xd

The full log is at:

https://pipelines.actions.githubusercontent.com/4WG3RDC5LrvSQSfVuzaeJ6lLFmXDn3iE4xIDQGf4ZMGoiw0ciN/_apis/pipelines/1/runs/353/signedlogcontent/3?urlExpires=2021-06-01T01%3A26%3A49.3916756Z&urlSigningMethod=HMACV1&urlSignature=GKjPRIscFdqMrNb5DG83p7Siwo2LTAS%2FCmjMn8ZP%2FRE%3D

I think the pyerfa-2.0.0 package is likely compiled with numpy 1.20 API which means it is not backward compatible with numpy 1.18. This is probably unintended. There is a way to pin numpy to an older version during package compilation. I suspect 1.16 API is still the main stream and recommend pin to 1.16 or earlier if possible.

If a 1.20 API is really needed, I suggest declare a requirement of numpy >= 1.20 in requirements.

Thanks!

### PR DESCRIPTION
**Pull request by maxnoe**
This should fix #18 by compiling against the oldest supported numpy version by pyerfa, as detailed here:
https://conda-forge.org/docs/maintainer/knowledge_base.html#building-against-numpy

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maxnoe** [comment]
@conda-forge-admin, please rerender

**Comment by maxnoe** [comment]
ok, finally looks like it's working after I update with `conda smithy rerender` locally, somehow the bot didn't make the same changes.

I took the pinnings / not pinnings of numpy from the sklearn recipe, which seems to be correct.

**Review by avalentino — APPROVED** [review]
LGTM

**Comment by avalentino** [comment]
Thanks @maxnoe

**Pull request merged**
